# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20170921_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='img',
            field=models.ImageField(default=1, upload_to='upload/'),
            preserve_default=False,
        ),
    ]
